[MySQL]
Endpoint="127.0.0.1"
Port=3306
Database="testdb"
Username="root"
Password="lowkey2046"

[trackers]
Enable = ["process", "tcp", "syscall"]

[process]
container_id = 7895212
process_id = 100
run_time = 50
fmt = "json"
[exporter]
Enable = ["prometheus", "json", "influxdb"]

[prometheus]
endpoint ="127.0.0.1"
port = 6789

[rules]
Enable = ["rule1", "rule2"]

[rule1]
type = "syscall"
name = "bpf..."
error_message = "error: bpf exec"

[rule2]
type = "file"
name = "/proc/xxx"
error_message = "error: bpf exec"


[seccomp]
allow = ["read","write", "connect"]